# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_modifier.ui'
#
# Created: Thu Jun 12 00:49:26 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 344)
        self.verticalLayout_7 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbModifier = QtGui.QLabel(Dialog)
        self.lbModifier.setObjectName("lbModifier")
        self.verticalLayout_2.addWidget(self.lbModifier)
        self.leModifier = QtGui.QLineEdit(Dialog)
        self.leModifier.setObjectName("leModifier")
        self.verticalLayout_2.addWidget(self.leModifier)
        self.lbCode = QtGui.QLabel(Dialog)
        self.lbCode.setObjectName("lbCode")
        self.verticalLayout_2.addWidget(self.lbCode)
        self.leCode = QtGui.QLineEdit(Dialog)
        self.leCode.setObjectName("leCode")
        self.verticalLayout_2.addWidget(self.leCode)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pbAddModifier = QtGui.QPushButton(Dialog)
        self.pbAddModifier.setObjectName("pbAddModifier")
        self.verticalLayout_3.addWidget(self.pbAddModifier)
        self.pbModifyModifier = QtGui.QPushButton(Dialog)
        self.pbModifyModifier.setObjectName("pbModifyModifier")
        self.verticalLayout_3.addWidget(self.pbModifyModifier)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetModifiersSets = QtGui.QTabWidget(Dialog)
        self.tabWidgetModifiersSets.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidgetModifiersSets.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidgetModifiersSets.setObjectName("tabWidgetModifiersSets")
        self.set1 = QtGui.QWidget()
        self.set1.setObjectName("set1")
        self.tabWidgetModifiersSets.addTab(self.set1, "")
        self.verticalLayout.addWidget(self.tabWidgetModifiersSets)
        self.lwModifiers = QtGui.QListWidget(Dialog)
        self.lwModifiers.setObjectName("lwModifiers")
        self.verticalLayout.addWidget(self.lwModifiers)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pbRemoveModifier = QtGui.QPushButton(Dialog)
        self.pbRemoveModifier.setObjectName("pbRemoveModifier")
        self.verticalLayout_4.addWidget(self.pbRemoveModifier)
        self.pbAddSet = QtGui.QPushButton(Dialog)
        self.pbAddSet.setObjectName("pbAddSet")
        self.verticalLayout_4.addWidget(self.pbAddSet)
        self.pbRemoveSet = QtGui.QPushButton(Dialog)
        self.pbRemoveSet.setObjectName("pbRemoveSet")
        self.verticalLayout_4.addWidget(self.pbRemoveSet)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pbCancel = QtGui.QPushButton(Dialog)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbOK = QtGui.QPushButton(Dialog)
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout_2.addWidget(self.pbOK)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)

        self.retranslateUi(Dialog)
        self.tabWidgetModifiersSets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Set modifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.lbModifier.setText(QtGui.QApplication.translate("Dialog", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.lbCode.setText(QtGui.QApplication.translate("Dialog", "Key code", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddModifier.setText(QtGui.QApplication.translate("Dialog", "-->", None, QtGui.QApplication.UnicodeUTF8))
        self.pbModifyModifier.setText(QtGui.QApplication.translate("Dialog", "<--", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetModifiersSets.setTabText(self.tabWidgetModifiersSets.indexOf(self.set1), QtGui.QApplication.translate("Dialog", "Set #1", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveModifier.setText(QtGui.QApplication.translate("Dialog", "Remove modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddSet.setText(QtGui.QApplication.translate("Dialog", "Add set of modifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveSet.setText(QtGui.QApplication.translate("Dialog", "Remove set of modifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOK.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))

