# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'observation.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(985, 590)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.leObservationId = QtWidgets.QLineEdit(self.layoutWidget)
        self.leObservationId.setObjectName("leObservationId")
        self.horizontalLayout_2.addWidget(self.leObservationId)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.dteDate = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dteDate.setCalendarPopup(True)
        self.dteDate.setObjectName("dteDate")
        self.horizontalLayout_2.addWidget(self.dteDate)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.teDescription = QtWidgets.QTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teDescription.sizePolicy().hasHeightForWidth())
        self.teDescription.setSizePolicy(sizePolicy)
        self.teDescription.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.teDescription.setAcceptDrops(False)
        self.teDescription.setObjectName("teDescription")
        self.verticalLayout_2.addWidget(self.teDescription)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_11.addWidget(self.label_3)
        self.twIndepVariables = QtWidgets.QTableWidget(self.layoutWidget2)
        self.twIndepVariables.setObjectName("twIndepVariables")
        self.twIndepVariables.setColumnCount(3)
        self.twIndepVariables.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twIndepVariables.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twIndepVariables.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twIndepVariables.setHorizontalHeaderItem(2, item)
        self.verticalLayout_11.addWidget(self.twIndepVariables)
        self.verticalLayout_12.addWidget(self.splitter)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbTimeOffset = QtWidgets.QLabel(self.layoutWidget)
        self.lbTimeOffset.setObjectName("lbTimeOffset")
        self.horizontalLayout_6.addWidget(self.lbTimeOffset)
        self.rbAdd = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbAdd.setChecked(True)
        self.rbAdd.setObjectName("rbAdd")
        self.horizontalLayout_6.addWidget(self.rbAdd)
        self.rbSubstract = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbSubstract.setObjectName("rbSubstract")
        self.horizontalLayout_6.addWidget(self.rbSubstract)
        self.leTimeOffset = QtWidgets.QLineEdit(self.layoutWidget)
        self.leTimeOffset.setObjectName("leTimeOffset")
        self.horizontalLayout_6.addWidget(self.leTimeOffset)
        self.teTimeOffset = QtWidgets.QTimeEdit(self.layoutWidget)
        self.teTimeOffset.setObjectName("teTimeOffset")
        self.horizontalLayout_6.addWidget(self.teTimeOffset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.layoutWidget3 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabProjectType = QtWidgets.QTabWidget(self.layoutWidget3)
        self.tabProjectType.setEnabled(True)
        self.tabProjectType.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabProjectType.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabProjectType.setUsesScrollButtons(False)
        self.tabProjectType.setDocumentMode(False)
        self.tabProjectType.setTabsClosable(False)
        self.tabProjectType.setMovable(False)
        self.tabProjectType.setObjectName("tabProjectType")
        self.tabVideo = QtWidgets.QWidget()
        self.tabVideo.setObjectName("tabVideo")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabVideo)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.tabVideo)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.twVideo1 = QtWidgets.QTableWidget(self.tabVideo)
        self.twVideo1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twVideo1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twVideo1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twVideo1.setObjectName("twVideo1")
        self.twVideo1.setColumnCount(5)
        self.twVideo1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo1.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_4.addWidget(self.twVideo1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbAddVideo = QtWidgets.QPushButton(self.tabVideo)
        self.pbAddVideo.setObjectName("pbAddVideo")
        self.verticalLayout.addWidget(self.pbAddVideo)
        self.pbRemoveVideo = QtWidgets.QPushButton(self.tabVideo)
        self.pbRemoveVideo.setObjectName("pbRemoveVideo")
        self.verticalLayout.addWidget(self.pbRemoveVideo)
        self.pbAddMediaFromDir = QtWidgets.QPushButton(self.tabVideo)
        self.pbAddMediaFromDir.setObjectName("pbAddMediaFromDir")
        self.verticalLayout.addWidget(self.pbAddMediaFromDir)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.cbVisualizeSpectrogram = QtWidgets.QCheckBox(self.tabVideo)
        self.cbVisualizeSpectrogram.setObjectName("cbVisualizeSpectrogram")
        self.verticalLayout_3.addWidget(self.cbVisualizeSpectrogram)
        self.cbCloseCurrentBehaviorsBetweenVideo = QtWidgets.QCheckBox(self.tabVideo)
        self.cbCloseCurrentBehaviorsBetweenVideo.setObjectName("cbCloseCurrentBehaviorsBetweenVideo")
        self.verticalLayout_3.addWidget(self.cbCloseCurrentBehaviorsBetweenVideo)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tabVideo)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.twVideo2 = QtWidgets.QTableWidget(self.tabVideo)
        self.twVideo2.setObjectName("twVideo2")
        self.twVideo2.setColumnCount(5)
        self.twVideo2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twVideo2.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_5.addWidget(self.twVideo2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pbAddVideo_2 = QtWidgets.QPushButton(self.tabVideo)
        self.pbAddVideo_2.setObjectName("pbAddVideo_2")
        self.verticalLayout_6.addWidget(self.pbAddVideo_2)
        self.pbRemoveVideo_2 = QtWidgets.QPushButton(self.tabVideo)
        self.pbRemoveVideo_2.setObjectName("pbRemoveVideo_2")
        self.verticalLayout_6.addWidget(self.pbRemoveVideo_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbTimeOffset_2 = QtWidgets.QLabel(self.tabVideo)
        self.lbTimeOffset_2.setObjectName("lbTimeOffset_2")
        self.horizontalLayout_7.addWidget(self.lbTimeOffset_2)
        self.rbEarlier = QtWidgets.QRadioButton(self.tabVideo)
        self.rbEarlier.setChecked(True)
        self.rbEarlier.setObjectName("rbEarlier")
        self.horizontalLayout_7.addWidget(self.rbEarlier)
        self.rbLater = QtWidgets.QRadioButton(self.tabVideo)
        self.rbLater.setObjectName("rbLater")
        self.horizontalLayout_7.addWidget(self.rbLater)
        self.leTimeOffset_2 = QtWidgets.QLineEdit(self.tabVideo)
        self.leTimeOffset_2.setObjectName("leTimeOffset_2")
        self.horizontalLayout_7.addWidget(self.leTimeOffset_2)
        self.teTimeOffset_2 = QtWidgets.QTimeEdit(self.tabVideo)
        self.teTimeOffset_2.setObjectName("teTimeOffset_2")
        self.horizontalLayout_7.addWidget(self.teTimeOffset_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.tabProjectType.addTab(self.tabVideo, "")
        self.tabLive = QtWidgets.QWidget()
        self.tabLive.setObjectName("tabLive")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabLive)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.tabLive)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.sbScanSampling = QtWidgets.QSpinBox(self.tabLive)
        self.sbScanSampling.setMaximum(1000000)
        self.sbScanSampling.setObjectName("sbScanSampling")
        self.horizontalLayout_8.addWidget(self.sbScanSampling)
        self.label_6 = QtWidgets.QLabel(self.tabLive)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.verticalLayout_10.addLayout(self.verticalLayout_8)
        self.tabProjectType.addTab(self.tabLive, "")
        self.verticalLayout_9.addWidget(self.tabProjectType)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbMediaAnalysis = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbMediaAnalysis.setFont(font)
        self.lbMediaAnalysis.setObjectName("lbMediaAnalysis")
        self.horizontalLayout.addWidget(self.lbMediaAnalysis)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.pbCancel = QtWidgets.QPushButton(self.layoutWidget3)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.pbSave = QtWidgets.QPushButton(self.layoutWidget3)
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout.addWidget(self.pbSave)
        self.pbLaunch = QtWidgets.QPushButton(self.layoutWidget3)
        self.pbLaunch.setObjectName("pbLaunch")
        self.horizontalLayout.addWidget(self.pbLaunch)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.verticalLayout_13.addWidget(self.splitter_2)

        self.retranslateUi(Form)
        self.tabProjectType.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "New observation"))
        self.label.setText(_translate("Form", "Observation id"))
        self.label_8.setText(_translate("Form", "Date"))
        self.dteDate.setDisplayFormat(_translate("Form", "yyyy-MM-dd hh:mm"))
        self.label_9.setText(_translate("Form", "Description"))
        self.label_3.setText(_translate("Form", "Independent variables"))
        item = self.twIndepVariables.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Variable"))
        item = self.twIndepVariables.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type"))
        item = self.twIndepVariables.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Value"))
        self.lbTimeOffset.setText(_translate("Form", "Time offset"))
        self.rbAdd.setText(_translate("Form", "Add"))
        self.rbSubstract.setText(_translate("Form", "Substract"))
        self.leTimeOffset.setText(_translate("Form", "0"))
        self.teTimeOffset.setDisplayFormat(_translate("Form", "hh:mm:ss.zzz"))
        self.label_5.setText(_translate("Form", "Media file paths"))
        item = self.twVideo1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Path"))
        item = self.twVideo1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Duration"))
        item = self.twVideo1.horizontalHeaderItem(2)
        item.setText(_translate("Form", "FPS"))
        item = self.twVideo1.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Video"))
        item = self.twVideo1.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Audio"))
        self.pbAddVideo.setText(_translate("Form", "Add media"))
        self.pbRemoveVideo.setText(_translate("Form", "Remove media"))
        self.pbAddMediaFromDir.setText(_translate("Form", "Add all media\n"
"from directory"))
        self.cbVisualizeSpectrogram.setText(_translate("Form", "Visualize spectrogram"))
        self.cbCloseCurrentBehaviorsBetweenVideo.setText(_translate("Form", "Stop ongoing state events between successive media files"))
        self.label_2.setText(_translate("Form", "Media file paths for second player (will be played simultaneously)"))
        item = self.twVideo2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Path"))
        item = self.twVideo2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Duration"))
        item = self.twVideo2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "FPS"))
        item = self.twVideo2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Video"))
        item = self.twVideo2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Audio"))
        self.pbAddVideo_2.setText(_translate("Form", "Add media"))
        self.pbRemoveVideo_2.setText(_translate("Form", "Remove media"))
        self.lbTimeOffset_2.setText(_translate("Form", "Time offset for second player"))
        self.rbEarlier.setText(_translate("Form", "Earlier"))
        self.rbLater.setText(_translate("Form", "Later"))
        self.leTimeOffset_2.setText(_translate("Form", "0"))
        self.teTimeOffset_2.setDisplayFormat(_translate("Form", "hh:mm:ss.zzz"))
        self.tabProjectType.setTabText(self.tabProjectType.indexOf(self.tabVideo), _translate("Form", "Media"))
        self.label_4.setText(_translate("Form", "Scan sampling every"))
        self.label_6.setText(_translate("Form", "seconds"))
        self.tabProjectType.setTabText(self.tabProjectType.indexOf(self.tabLive), _translate("Form", "Live"))
        self.lbMediaAnalysis.setText(_translate("Form", "BORIS"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.pbLaunch.setText(_translate("Form", "Start"))

