# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Thu Mar 26 12:34:47 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_prefDialog(object):
    def setupUi(self, prefDialog):
        prefDialog.setObjectName(_fromUtf8("prefDialog"))
        prefDialog.setWindowModality(QtCore.Qt.WindowModal)
        prefDialog.resize(694, 419)
        self.verticalLayout_5 = QtGui.QVBoxLayout(prefDialog)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(prefDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cbTimeFormat = QtGui.QComboBox(self.tab)
        self.cbTimeFormat.setObjectName(_fromUtf8("cbTimeFormat"))
        self.cbTimeFormat.addItem(_fromUtf8(""))
        self.cbTimeFormat.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbTimeFormat)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sbffSpeed = QtGui.QSpinBox(self.tab)
        self.sbffSpeed.setMinimum(0)
        self.sbffSpeed.setMaximum(10000)
        self.sbffSpeed.setProperty("value", 10)
        self.sbffSpeed.setObjectName(_fromUtf8("sbffSpeed"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sbffSpeed)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sbRepositionTimeOffset = QtGui.QSpinBox(self.tab)
        self.sbRepositionTimeOffset.setMinimum(-10000)
        self.sbRepositionTimeOffset.setMaximum(10000)
        self.sbRepositionTimeOffset.setProperty("value", -3)
        self.sbRepositionTimeOffset.setObjectName(_fromUtf8("sbRepositionTimeOffset"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sbRepositionTimeOffset)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.sbSpeedStep = QtGui.QDoubleSpinBox(self.tab)
        self.sbSpeedStep.setDecimals(1)
        self.sbSpeedStep.setMinimum(0.1)
        self.sbSpeedStep.setMaximum(1.0)
        self.sbSpeedStep.setSingleStep(0.1)
        self.sbSpeedStep.setProperty("value", 0.1)
        self.sbSpeedStep.setObjectName(_fromUtf8("sbSpeedStep"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.sbSpeedStep)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.sbAutomaticBackup = QtGui.QSpinBox(self.tab)
        self.sbAutomaticBackup.setMinimum(-10000)
        self.sbAutomaticBackup.setMaximum(10000)
        self.sbAutomaticBackup.setProperty("value", 10)
        self.sbAutomaticBackup.setObjectName(_fromUtf8("sbAutomaticBackup"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.sbAutomaticBackup)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.leSeparator = QtGui.QLineEdit(self.tab)
        self.leSeparator.setObjectName(_fromUtf8("leSeparator"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.leSeparator)
        self.cbConfirmSound = QtGui.QCheckBox(self.tab)
        self.cbConfirmSound.setObjectName(_fromUtf8("cbConfirmSound"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.cbConfirmSound)
        self.cbEmbedPlayer = QtGui.QCheckBox(self.tab)
        self.cbEmbedPlayer.setObjectName(_fromUtf8("cbEmbedPlayer"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.cbEmbedPlayer)
        self.cbAlertNoFocalSubject = QtGui.QCheckBox(self.tab)
        self.cbAlertNoFocalSubject.setObjectName(_fromUtf8("cbAlertNoFocalSubject"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.cbAlertNoFocalSubject)
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.cbAllowFrameByFrameMode = QtGui.QCheckBox(self.tab_2)
        self.cbAllowFrameByFrameMode.setObjectName(_fromUtf8("cbAllowFrameByFrameMode"))
        self.verticalLayout_3.addWidget(self.cbAllowFrameByFrameMode)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbFFmpeg = QtGui.QLabel(self.tab_2)
        self.lbFFmpeg.setObjectName(_fromUtf8("lbFFmpeg"))
        self.horizontalLayout.addWidget(self.lbFFmpeg)
        self.leFFmpegPath = QtGui.QLineEdit(self.tab_2)
        self.leFFmpegPath.setObjectName(_fromUtf8("leFFmpegPath"))
        self.horizontalLayout.addWidget(self.leFFmpegPath)
        self.pbBrowseFFmpeg = QtGui.QPushButton(self.tab_2)
        self.pbBrowseFFmpeg.setObjectName(_fromUtf8("pbBrowseFFmpeg"))
        self.horizontalLayout.addWidget(self.pbBrowseFFmpeg)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbFFmpegCacheDir = QtGui.QLabel(self.tab_2)
        self.lbFFmpegCacheDir.setObjectName(_fromUtf8("lbFFmpegCacheDir"))
        self.horizontalLayout_3.addWidget(self.lbFFmpegCacheDir)
        self.leFFmpegCacheDir = QtGui.QLineEdit(self.tab_2)
        self.leFFmpegCacheDir.setObjectName(_fromUtf8("leFFmpegCacheDir"))
        self.horizontalLayout_3.addWidget(self.leFFmpegCacheDir)
        self.pbBrowseFFmpegCacheDir = QtGui.QPushButton(self.tab_2)
        self.pbBrowseFFmpegCacheDir.setObjectName(_fromUtf8("pbBrowseFFmpegCacheDir"))
        self.horizontalLayout_3.addWidget(self.pbBrowseFFmpegCacheDir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbFFmpegCacheDirMaxSize = QtGui.QLabel(self.tab_2)
        self.lbFFmpegCacheDirMaxSize.setObjectName(_fromUtf8("lbFFmpegCacheDirMaxSize"))
        self.horizontalLayout_4.addWidget(self.lbFFmpegCacheDirMaxSize)
        self.sbFFmpegCacheDirMaxSize = QtGui.QSpinBox(self.tab_2)
        self.sbFFmpegCacheDirMaxSize.setMaximum(10000)
        self.sbFFmpegCacheDirMaxSize.setSingleStep(10)
        self.sbFFmpegCacheDirMaxSize.setObjectName(_fromUtf8("sbFFmpegCacheDirMaxSize"))
        self.horizontalLayout_4.addWidget(self.sbFFmpegCacheDirMaxSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(241, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbCancel = QtGui.QPushButton(prefDialog)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbOK = QtGui.QPushButton(prefDialog)
        self.pbOK.setObjectName(_fromUtf8("pbOK"))
        self.horizontalLayout_2.addWidget(self.pbOK)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(prefDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(prefDialog)

    def retranslateUi(self, prefDialog):
        prefDialog.setWindowTitle(_translate("prefDialog", "Preferences", None))
        self.label.setText(_translate("prefDialog", "Default project time format", None))
        self.cbTimeFormat.setItemText(0, _translate("prefDialog", "seconds", None))
        self.cbTimeFormat.setItemText(1, _translate("prefDialog", "hh:mm:ss.mss", None))
        self.label_4.setText(_translate("prefDialog", "Fast forward/backward speed (seconds)", None))
        self.label_2.setText(_translate("prefDialog", "Time offset for video/audio reposition (seconds)", None))
        self.label_5.setText(_translate("prefDialog", "Playback speed step value", None))
        self.label_6.setText(_translate("prefDialog", "Automatic backup every (minutes)", None))
        self.label_3.setText(_translate("prefDialog", "Separator for behavioural strings (events export)", None))
        self.leSeparator.setText(_translate("prefDialog", "|", None))
        self.cbConfirmSound.setText(_translate("prefDialog", "Play sound when a key is pressed", None))
        self.cbEmbedPlayer.setText(_translate("prefDialog", "Embed media player in main window (program must be restarted)", None))
        self.cbAlertNoFocalSubject.setText(_translate("prefDialog", "Alert if focal subject is not set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("prefDialog", "Project", None))
        self.label_14.setText(_translate("prefDialog", "The frame-by-frame mode requires the FFmpeg program. See https://www.ffmpeg.org ", None))
        self.cbAllowFrameByFrameMode.setText(_translate("prefDialog", "Allow the frame-by-frame mode", None))
        self.lbFFmpeg.setText(_translate("prefDialog", "Path for FFmpeg", None))
        self.pbBrowseFFmpeg.setText(_translate("prefDialog", "...", None))
        self.lbFFmpegCacheDir.setText(_translate("prefDialog", "FFmpeg cache directory", None))
        self.pbBrowseFFmpegCacheDir.setText(_translate("prefDialog", "...", None))
        self.lbFFmpegCacheDirMaxSize.setText(_translate("prefDialog", "FFmpeg cache directory max size (Mb)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("prefDialog", "Frame-by-frame mode", None))
        self.pbCancel.setText(_translate("prefDialog", "Cancel", None))
        self.pbOK.setText(_translate("prefDialog", "OK", None))

