# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Sat Nov  8 13:59:36 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_prefDialog(object):
    def setupUi(self, prefDialog):
        prefDialog.setObjectName("prefDialog")
        prefDialog.setWindowModality(QtCore.Qt.WindowModal)
        prefDialog.resize(694, 419)
        self.verticalLayout_5 = QtGui.QVBoxLayout(prefDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(prefDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cbTimeFormat = QtGui.QComboBox(self.tab)
        self.cbTimeFormat.setObjectName("cbTimeFormat")
        self.cbTimeFormat.addItem("")
        self.cbTimeFormat.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbTimeFormat)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.sbffSpeed = QtGui.QSpinBox(self.tab)
        self.sbffSpeed.setMinimum(0)
        self.sbffSpeed.setMaximum(10000)
        self.sbffSpeed.setProperty("value", 10)
        self.sbffSpeed.setObjectName("sbffSpeed")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sbffSpeed)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sbRepositionTimeOffset = QtGui.QSpinBox(self.tab)
        self.sbRepositionTimeOffset.setMinimum(-10000)
        self.sbRepositionTimeOffset.setMaximum(10000)
        self.sbRepositionTimeOffset.setProperty("value", -3)
        self.sbRepositionTimeOffset.setObjectName("sbRepositionTimeOffset")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.sbRepositionTimeOffset)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.sbSpeedStep = QtGui.QDoubleSpinBox(self.tab)
        self.sbSpeedStep.setDecimals(1)
        self.sbSpeedStep.setMinimum(0.1)
        self.sbSpeedStep.setMaximum(1.0)
        self.sbSpeedStep.setSingleStep(0.1)
        self.sbSpeedStep.setProperty("value", 0.1)
        self.sbSpeedStep.setObjectName("sbSpeedStep")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.sbSpeedStep)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.sbAutomaticBackup = QtGui.QSpinBox(self.tab)
        self.sbAutomaticBackup.setMinimum(-10000)
        self.sbAutomaticBackup.setMaximum(10000)
        self.sbAutomaticBackup.setProperty("value", 10)
        self.sbAutomaticBackup.setObjectName("sbAutomaticBackup")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.sbAutomaticBackup)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.leSeparator = QtGui.QLineEdit(self.tab)
        self.leSeparator.setObjectName("leSeparator")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.leSeparator)
        self.cbConfirmSound = QtGui.QCheckBox(self.tab)
        self.cbConfirmSound.setObjectName("cbConfirmSound")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.cbConfirmSound)
        self.cbEmbedPlayer = QtGui.QCheckBox(self.tab)
        self.cbEmbedPlayer.setObjectName("cbEmbedPlayer")
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.cbEmbedPlayer)
        self.cbAlertNoFocalSubject = QtGui.QCheckBox(self.tab)
        self.cbAlertNoFocalSubject.setObjectName("cbAlertNoFocalSubject")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.cbAlertNoFocalSubject)
        self.verticalLayout.addLayout(self.formLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.cbAllowFrameByFrameMode = QtGui.QCheckBox(self.tab_2)
        self.cbAllowFrameByFrameMode.setObjectName("cbAllowFrameByFrameMode")
        self.verticalLayout_3.addWidget(self.cbAllowFrameByFrameMode)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbFFmpeg = QtGui.QLabel(self.tab_2)
        self.lbFFmpeg.setObjectName("lbFFmpeg")
        self.horizontalLayout.addWidget(self.lbFFmpeg)
        self.leFFmpegPath = QtGui.QLineEdit(self.tab_2)
        self.leFFmpegPath.setObjectName("leFFmpegPath")
        self.horizontalLayout.addWidget(self.leFFmpegPath)
        self.pbBrowseFFmpeg = QtGui.QPushButton(self.tab_2)
        self.pbBrowseFFmpeg.setObjectName("pbBrowseFFmpeg")
        self.horizontalLayout.addWidget(self.pbBrowseFFmpeg)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbFFmpegCacheDir = QtGui.QLabel(self.tab_2)
        self.lbFFmpegCacheDir.setObjectName("lbFFmpegCacheDir")
        self.horizontalLayout_3.addWidget(self.lbFFmpegCacheDir)
        self.leFFmpegCacheDir = QtGui.QLineEdit(self.tab_2)
        self.leFFmpegCacheDir.setObjectName("leFFmpegCacheDir")
        self.horizontalLayout_3.addWidget(self.leFFmpegCacheDir)
        self.pbBrowseFFmpegCacheDir = QtGui.QPushButton(self.tab_2)
        self.pbBrowseFFmpegCacheDir.setObjectName("pbBrowseFFmpegCacheDir")
        self.horizontalLayout_3.addWidget(self.pbBrowseFFmpegCacheDir)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbFFmpegCacheDirMaxSize = QtGui.QLabel(self.tab_2)
        self.lbFFmpegCacheDirMaxSize.setObjectName("lbFFmpegCacheDirMaxSize")
        self.horizontalLayout_4.addWidget(self.lbFFmpegCacheDirMaxSize)
        self.sbFFmpegCacheDirMaxSize = QtGui.QSpinBox(self.tab_2)
        self.sbFFmpegCacheDirMaxSize.setMaximum(10000)
        self.sbFFmpegCacheDirMaxSize.setSingleStep(10)
        self.sbFFmpegCacheDirMaxSize.setObjectName("sbFFmpegCacheDirMaxSize")
        self.horizontalLayout_4.addWidget(self.sbFFmpegCacheDirMaxSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(241, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pbCancel = QtGui.QPushButton(prefDialog)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbOK = QtGui.QPushButton(prefDialog)
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout_2.addWidget(self.pbOK)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)

        self.retranslateUi(prefDialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(prefDialog)

    def retranslateUi(self, prefDialog):
        prefDialog.setWindowTitle(QtGui.QApplication.translate("prefDialog", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("prefDialog", "Default project time format", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimeFormat.setItemText(0, QtGui.QApplication.translate("prefDialog", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.cbTimeFormat.setItemText(1, QtGui.QApplication.translate("prefDialog", "hh:mm:ss.mss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("prefDialog", "Fast forward/backward speed (seconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("prefDialog", "Time offset for video/audio reposition (seconds)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("prefDialog", "Playback speed step value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("prefDialog", "Automatic backup every (minutes)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("prefDialog", "Separator for behavioural strings (events export)", None, QtGui.QApplication.UnicodeUTF8))
        self.leSeparator.setText(QtGui.QApplication.translate("prefDialog", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.cbConfirmSound.setText(QtGui.QApplication.translate("prefDialog", "Play sound when a key is pressed", None, QtGui.QApplication.UnicodeUTF8))
        self.cbEmbedPlayer.setText(QtGui.QApplication.translate("prefDialog", "Embed media player in main window (program must be restarted)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlertNoFocalSubject.setText(QtGui.QApplication.translate("prefDialog", "Alert if focal subject is not set", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("prefDialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("prefDialog", "The frame-by-frame mode requires the FFmpeg program. See https://www.ffmpeg.org ", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAllowFrameByFrameMode.setText(QtGui.QApplication.translate("prefDialog", "Allow the frame-by-frame mode", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFFmpeg.setText(QtGui.QApplication.translate("prefDialog", "Path for FFmpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.pbBrowseFFmpeg.setText(QtGui.QApplication.translate("prefDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFFmpegCacheDir.setText(QtGui.QApplication.translate("prefDialog", "FFmpeg cache directory", None, QtGui.QApplication.UnicodeUTF8))
        self.pbBrowseFFmpegCacheDir.setText(QtGui.QApplication.translate("prefDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lbFFmpegCacheDirMaxSize.setText(QtGui.QApplication.translate("prefDialog", "FFmpeg cache directory max size (Mb)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("prefDialog", "Frame-by-frame mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("prefDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOK.setText(QtGui.QApplication.translate("prefDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))

