# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created: Fri Mar 21 23:04:10 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgProject(object):
    def setupUi(self, dlgProject):
        dlgProject.setObjectName("dlgProject")
        dlgProject.resize(829, 562)
        self.verticalLayout_7 = QtGui.QVBoxLayout(dlgProject)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabProject = QtGui.QTabWidget(dlgProject)
        self.tabProject.setObjectName("tabProject")
        self.tabInformation = QtGui.QWidget()
        self.tabInformation.setObjectName("tabInformation")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabInformation)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.tabInformation)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label)
        self.leProjectName = QtGui.QLineEdit(self.tabInformation)
        self.leProjectName.setObjectName("leProjectName")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leProjectName)
        self.label_7 = QtGui.QLabel(self.tabInformation)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.dteDate = QtGui.QDateTimeEdit(self.tabInformation)
        self.dteDate.setObjectName("dteDate")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dteDate)
        self.label_6 = QtGui.QLabel(self.tabInformation)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.label_6)
        self.teDescription = QtGui.QPlainTextEdit(self.tabInformation)
        self.teDescription.setObjectName("teDescription")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.teDescription)
        self.lbTimeFormat = QtGui.QLabel(self.tabInformation)
        self.lbTimeFormat.setObjectName("lbTimeFormat")
        self.formLayout.setWidget(8, QtGui.QFormLayout.SpanningRole, self.lbTimeFormat)
        self.rbSeconds = QtGui.QRadioButton(self.tabInformation)
        self.rbSeconds.setChecked(True)
        self.rbSeconds.setObjectName("rbSeconds")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.rbSeconds)
        self.rbHMS = QtGui.QRadioButton(self.tabInformation)
        self.rbHMS.setObjectName("rbHMS")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.rbHMS)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.tabProject.addTab(self.tabInformation, "")
        self.tabSubjects = QtGui.QWidget()
        self.tabSubjects.setObjectName("tabSubjects")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tabSubjects)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.twSubjects = QtGui.QTableWidget(self.tabSubjects)
        self.twSubjects.setAutoFillBackground(False)
        self.twSubjects.setFrameShadow(QtGui.QFrame.Sunken)
        self.twSubjects.setMidLineWidth(0)
        self.twSubjects.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twSubjects.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twSubjects.setObjectName("twSubjects")
        self.twSubjects.setColumnCount(2)
        self.twSubjects.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twSubjects.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twSubjects.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_12.addWidget(self.twSubjects)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pbAddSubject = QtGui.QPushButton(self.tabSubjects)
        self.pbAddSubject.setObjectName("pbAddSubject")
        self.verticalLayout_15.addWidget(self.pbAddSubject)
        self.pbRemoveSubject = QtGui.QPushButton(self.tabSubjects)
        self.pbRemoveSubject.setObjectName("pbRemoveSubject")
        self.verticalLayout_15.addWidget(self.pbRemoveSubject)
        self.gbSorting = QtGui.QGroupBox(self.tabSubjects)
        self.gbSorting.setObjectName("gbSorting")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbSorting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cbAlphabeticalOrder = QtGui.QCheckBox(self.gbSorting)
        self.cbAlphabeticalOrder.setObjectName("cbAlphabeticalOrder")
        self.verticalLayout_3.addWidget(self.cbAlphabeticalOrder)
        self.pbUp = QtGui.QPushButton(self.gbSorting)
        self.pbUp.setObjectName("pbUp")
        self.verticalLayout_3.addWidget(self.pbUp)
        self.pbDown = QtGui.QPushButton(self.gbSorting)
        self.pbDown.setObjectName("pbDown")
        self.verticalLayout_3.addWidget(self.pbDown)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_15.addWidget(self.gbSorting)
        self.pbImportSubjectsFromProject = QtGui.QPushButton(self.tabSubjects)
        self.pbImportSubjectsFromProject.setObjectName("pbImportSubjectsFromProject")
        self.verticalLayout_15.addWidget(self.pbImportSubjectsFromProject)
        self.pbLoadSubjects = QtGui.QPushButton(self.tabSubjects)
        self.pbLoadSubjects.setEnabled(True)
        self.pbLoadSubjects.setObjectName("pbLoadSubjects")
        self.verticalLayout_15.addWidget(self.pbLoadSubjects)
        self.pbSaveSubjects = QtGui.QPushButton(self.tabSubjects)
        self.pbSaveSubjects.setEnabled(True)
        self.pbSaveSubjects.setObjectName("pbSaveSubjects")
        self.verticalLayout_15.addWidget(self.pbSaveSubjects)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.lbSubjectsState = QtGui.QLabel(self.tabSubjects)
        self.lbSubjectsState.setObjectName("lbSubjectsState")
        self.verticalLayout_14.addWidget(self.lbSubjectsState)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.tabProject.addTab(self.tabSubjects, "")
        self.tabConfiguration = QtGui.QWidget()
        self.tabConfiguration.setObjectName("tabConfiguration")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabConfiguration)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.twBehaviors = QtGui.QTableWidget(self.tabConfiguration)
        self.twBehaviors.setAutoFillBackground(False)
        self.twBehaviors.setFrameShadow(QtGui.QFrame.Sunken)
        self.twBehaviors.setMidLineWidth(0)
        self.twBehaviors.setAlternatingRowColors(True)
        self.twBehaviors.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twBehaviors.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twBehaviors.setObjectName("twBehaviors")
        self.twBehaviors.setColumnCount(6)
        self.twBehaviors.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(5, item)
        self.twBehaviors.horizontalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_11.addWidget(self.twBehaviors)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pbAddObservation = QtGui.QPushButton(self.tabConfiguration)
        self.pbAddObservation.setObjectName("pbAddObservation")
        self.verticalLayout_11.addWidget(self.pbAddObservation)
        self.pbClone = QtGui.QPushButton(self.tabConfiguration)
        self.pbClone.setObjectName("pbClone")
        self.verticalLayout_11.addWidget(self.pbClone)
        self.pbRemoveBehavior = QtGui.QPushButton(self.tabConfiguration)
        self.pbRemoveBehavior.setObjectName("pbRemoveBehavior")
        self.verticalLayout_11.addWidget(self.pbRemoveBehavior)
        self.pbRemoveAllBehaviors = QtGui.QPushButton(self.tabConfiguration)
        self.pbRemoveAllBehaviors.setObjectName("pbRemoveAllBehaviors")
        self.verticalLayout_11.addWidget(self.pbRemoveAllBehaviors)
        self.pbExclusionMatrix = QtGui.QPushButton(self.tabConfiguration)
        self.pbExclusionMatrix.setObjectName("pbExclusionMatrix")
        self.verticalLayout_11.addWidget(self.pbExclusionMatrix)
        self.groupBox = QtGui.QGroupBox(self.tabConfiguration)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.cbAlphabeticalOrder_behavior = QtGui.QCheckBox(self.groupBox)
        self.cbAlphabeticalOrder_behavior.setObjectName("cbAlphabeticalOrder_behavior")
        self.verticalLayout_8.addWidget(self.cbAlphabeticalOrder_behavior)
        self.pbUp_behavior = QtGui.QPushButton(self.groupBox)
        self.pbUp_behavior.setObjectName("pbUp_behavior")
        self.verticalLayout_8.addWidget(self.pbUp_behavior)
        self.pbDown_behavior = QtGui.QPushButton(self.groupBox)
        self.pbDown_behavior.setObjectName("pbDown_behavior")
        self.verticalLayout_8.addWidget(self.pbDown_behavior)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.pbImportBehaviorsFromProject = QtGui.QPushButton(self.tabConfiguration)
        self.pbImportBehaviorsFromProject.setObjectName("pbImportBehaviorsFromProject")
        self.verticalLayout_11.addWidget(self.pbImportBehaviorsFromProject)
        self.pbLoadConfiguration = QtGui.QPushButton(self.tabConfiguration)
        self.pbLoadConfiguration.setObjectName("pbLoadConfiguration")
        self.verticalLayout_11.addWidget(self.pbLoadConfiguration)
        self.pbSaveConfiguration = QtGui.QPushButton(self.tabConfiguration)
        self.pbSaveConfiguration.setObjectName("pbSaveConfiguration")
        self.verticalLayout_11.addWidget(self.pbSaveConfiguration)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.lbObservationsState = QtGui.QLabel(self.tabConfiguration)
        self.lbObservationsState.setObjectName("lbObservationsState")
        self.verticalLayout_5.addWidget(self.lbObservationsState)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.tabProject.addTab(self.tabConfiguration, "")
        self.tabIndependentVariables = QtGui.QWidget()
        self.tabIndependentVariables.setObjectName("tabIndependentVariables")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tabIndependentVariables)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.twVariables = QtGui.QTableWidget(self.tabIndependentVariables)
        self.twVariables.setAutoFillBackground(False)
        self.twVariables.setFrameShadow(QtGui.QFrame.Sunken)
        self.twVariables.setMidLineWidth(0)
        self.twVariables.setAlternatingRowColors(True)
        self.twVariables.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twVariables.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twVariables.setObjectName("twVariables")
        self.twVariables.setColumnCount(4)
        self.twVariables.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(3, item)
        self.twVariables.horizontalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_13.addWidget(self.twVariables)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pbAddVariable = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbAddVariable.setObjectName("pbAddVariable")
        self.verticalLayout_12.addWidget(self.pbAddVariable)
        self.pbRemoveVariable = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbRemoveVariable.setObjectName("pbRemoveVariable")
        self.verticalLayout_12.addWidget(self.pbRemoveVariable)
        self.groupBox_2 = QtGui.QGroupBox(self.tabIndependentVariables)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.cbAlphabeticalOrderVar = QtGui.QCheckBox(self.groupBox_2)
        self.cbAlphabeticalOrderVar.setObjectName("cbAlphabeticalOrderVar")
        self.verticalLayout_17.addWidget(self.cbAlphabeticalOrderVar)
        self.pbUpVar = QtGui.QPushButton(self.groupBox_2)
        self.pbUpVar.setObjectName("pbUpVar")
        self.verticalLayout_17.addWidget(self.pbUpVar)
        self.pbDownVar = QtGui.QPushButton(self.groupBox_2)
        self.pbDownVar.setObjectName("pbDownVar")
        self.verticalLayout_17.addWidget(self.pbDownVar)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem3)
        self.verticalLayout_13.addLayout(self.verticalLayout_17)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.pbImportVarFromProject = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbImportVarFromProject.setObjectName("pbImportVarFromProject")
        self.verticalLayout_12.addWidget(self.pbImportVarFromProject)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_18.addLayout(self.horizontalLayout_13)
        self.tabProject.addTab(self.tabIndependentVariables, "")
        self.tabObservations = QtGui.QWidget()
        self.tabObservations.setObjectName("tabObservations")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabObservations)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.twObservations = QtGui.QTableWidget(self.tabObservations)
        self.twObservations.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twObservations.setDragDropOverwriteMode(False)
        self.twObservations.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.twObservations.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twObservations.setObjectName("twObservations")
        self.twObservations.setColumnCount(4)
        self.twObservations.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(3, item)
        self.horizontalLayout.addWidget(self.twObservations)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbRemoveObservation = QtGui.QPushButton(self.tabObservations)
        self.pbRemoveObservation.setObjectName("pbRemoveObservation")
        self.verticalLayout.addWidget(self.pbRemoveObservation)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabProject.addTab(self.tabObservations, "")
        self.verticalLayout_6.addWidget(self.tabProject)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pbCancel = QtGui.QPushButton(dlgProject)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_4.addWidget(self.pbCancel)
        self.pbOK = QtGui.QPushButton(dlgProject)
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout_4.addWidget(self.pbOK)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)

        self.retranslateUi(dlgProject)
        self.tabProject.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(dlgProject)

    def retranslateUi(self, dlgProject):
        dlgProject.setWindowTitle(QtGui.QApplication.translate("dlgProject", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dlgProject", "Project name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dlgProject", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dlgProject", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTimeFormat.setText(QtGui.QApplication.translate("dlgProject", "Time format", None, QtGui.QApplication.UnicodeUTF8))
        self.rbSeconds.setText(QtGui.QApplication.translate("dlgProject", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.rbHMS.setText(QtGui.QApplication.translate("dlgProject", "hh:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabInformation), QtGui.QApplication.translate("dlgProject", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.twSubjects.setSortingEnabled(False)
        self.twSubjects.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("dlgProject", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.twSubjects.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("dlgProject", "Subject name", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddSubject.setText(QtGui.QApplication.translate("dlgProject", "Add subject", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveSubject.setText(QtGui.QApplication.translate("dlgProject", "Remove subject", None, QtGui.QApplication.UnicodeUTF8))
        self.gbSorting.setTitle(QtGui.QApplication.translate("dlgProject", "Sorting", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlphabeticalOrder.setText(QtGui.QApplication.translate("dlgProject", "Alphabetical order", None, QtGui.QApplication.UnicodeUTF8))
        self.pbUp.setText(QtGui.QApplication.translate("dlgProject", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDown.setText(QtGui.QApplication.translate("dlgProject", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportSubjectsFromProject.setText(QtGui.QApplication.translate("dlgProject", "Import from project", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLoadSubjects.setText(QtGui.QApplication.translate("dlgProject", "Load subjects from file", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveSubjects.setText(QtGui.QApplication.translate("dlgProject", "Save subjects to file", None, QtGui.QApplication.UnicodeUTF8))
        self.lbSubjectsState.setText(QtGui.QApplication.translate("dlgProject", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabSubjects), QtGui.QApplication.translate("dlgProject", "Subjects", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.setSortingEnabled(True)
        self.twBehaviors.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("dlgProject", "Behavior type", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("dlgProject", "Key", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("dlgProject", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("dlgProject", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("dlgProject", "Modifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.twBehaviors.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("dlgProject", "Exclude", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddObservation.setText(QtGui.QApplication.translate("dlgProject", "Add behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.pbClone.setText(QtGui.QApplication.translate("dlgProject", "Clone behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveBehavior.setText(QtGui.QApplication.translate("dlgProject", "Remove behavior", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveAllBehaviors.setText(QtGui.QApplication.translate("dlgProject", "Remove all behaviors", None, QtGui.QApplication.UnicodeUTF8))
        self.pbExclusionMatrix.setText(QtGui.QApplication.translate("dlgProject", "Exclusion matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dlgProject", "Sorting", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlphabeticalOrder_behavior.setText(QtGui.QApplication.translate("dlgProject", "Alphabetical order", None, QtGui.QApplication.UnicodeUTF8))
        self.pbUp_behavior.setText(QtGui.QApplication.translate("dlgProject", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDown_behavior.setText(QtGui.QApplication.translate("dlgProject", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportBehaviorsFromProject.setText(QtGui.QApplication.translate("dlgProject", "Import from project", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLoadConfiguration.setText(QtGui.QApplication.translate("dlgProject", "Load behaviors from file", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveConfiguration.setText(QtGui.QApplication.translate("dlgProject", "Save behaviors to file", None, QtGui.QApplication.UnicodeUTF8))
        self.lbObservationsState.setText(QtGui.QApplication.translate("dlgProject", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabConfiguration), QtGui.QApplication.translate("dlgProject", "Configuration of behaviors", None, QtGui.QApplication.UnicodeUTF8))
        self.twVariables.setSortingEnabled(True)
        self.twVariables.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("dlgProject", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.twVariables.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("dlgProject", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.twVariables.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("dlgProject", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.twVariables.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("dlgProject", "Predefined value", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddVariable.setText(QtGui.QApplication.translate("dlgProject", "Add variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveVariable.setText(QtGui.QApplication.translate("dlgProject", "Remove variable", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dlgProject", "Sorting", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlphabeticalOrderVar.setText(QtGui.QApplication.translate("dlgProject", "Alphabetical order", None, QtGui.QApplication.UnicodeUTF8))
        self.pbUpVar.setText(QtGui.QApplication.translate("dlgProject", "Move up", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDownVar.setText(QtGui.QApplication.translate("dlgProject", "Move down", None, QtGui.QApplication.UnicodeUTF8))
        self.pbImportVarFromProject.setText(QtGui.QApplication.translate("dlgProject", "Import from project", None, QtGui.QApplication.UnicodeUTF8))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabIndependentVariables), QtGui.QApplication.translate("dlgProject", "Independent variables", None, QtGui.QApplication.UnicodeUTF8))
        self.twObservations.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("dlgProject", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.twObservations.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("dlgProject", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.twObservations.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("dlgProject", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.twObservations.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("dlgProject", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveObservation.setText(QtGui.QApplication.translate("dlgProject", "Remove observation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabObservations), QtGui.QApplication.translate("dlgProject", "Observations", None, QtGui.QApplication.UnicodeUTF8))
        self.pbCancel.setText(QtGui.QApplication.translate("dlgProject", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOK.setText(QtGui.QApplication.translate("dlgProject", "OK", None, QtGui.QApplication.UnicodeUTF8))

