p = {
 "time_format":"hh:mm:ss",
 "project_name":"test",
 "project_date":"2016-11-27T01:55:22",
 "subjects_conf":{
  "1":{
   "name":"subject2",
   "description":"",
   "key":"2"
  },
  "0":{
   "name":"subject1",
   "description":"",
   "key":"1"
  }
 },
 "behavioral_categories":[],
 "coding_map":{},
 "observations":{
  "2":{
   "date":"2016-12-01T23:01:31",
   "file":{
    "1":[
     "/home/olivier/Downloads/video1.avi"
    ],
    "2":[
     "/home/olivier/Downloads/video2.avi"
    ]
   },
   "type":"MEDIA",
   "time offset second player":0.0,
   "visualize_spectrogram":false,
   "time offset":0.0,
   "independent_variables":{
    "b":"",
    "a":"",
    "c":"111"
   },
   "close_behaviors_between_videos":false,
   "events":[],
   "description":"",
   "media_info":{
    "length":{
     "/home/olivier/Downloads/video1.avi":225.64,
     "/home/olivier/Downloads/video2.avi":300.0
    },
    "hasAudio":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/video2.avi":true
    },
    "hasVideo":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/video2.avi":true
    },
    "fps":{
     "/home/olivier/Downloads/video1.avi":25.0,
     "/home/olivier/Downloads/video2.avi":25.0
    }
   }
  },
  "obs1":{
   "date":"2016-11-27T01:57:26",
   "file":{
    "1":[
     "/home/olivier/Downloads/50FPS.mp4"
    ],
    "2":[]
   },
   "type":"MEDIA",
   "time offset second player":0.0,
   "visualize_spectrogram":false,
   "time offset":0.0,
   "independent_variables":{
    "b":"ssssss",
    "a":"12",
    "c":"111"
   },
   "close_behaviors_between_videos":false,
   "events":[
    [
     3.3,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     7.75,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     9.9,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     16.2,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     18.35,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     24.475,
     "subject1",
     "s",
     "",
     ""
    ],
    [
     38.425,
     "subject2",
     "s",
     "",
     ""
    ],
    [
     46.1,
     "subject2",
     "s",
     "",
     ""
    ]
   ],
   "description":"",
   "media_info":{
    "length":{
     "/home/olivier/Downloads/50FPS.mp4":180.05
    },
    "hasAudio":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "hasVideo":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "fps":{
     "/home/olivier/Downloads/50FPS.mp4":50.0
    }
   }
  },
  "offset positif":{
   "date":"2016-12-10T15:44:57",
   "file":{
    "1":[
     "/home/olivier/Downloads/50FPS.mp4"
    ],
    "2":[
     "/home/olivier/Downloads/50FPS.mp4"
    ]
   },
   "type":"MEDIA",
   "time offset second player":20.0,
   "visualize_spectrogram":false,
   "time offset":0.0,
   "independent_variables":{
    "b":"",
    "a":"",
    "c":"111"
   },
   "close_behaviors_between_videos":false,
   "events":[
    [
     22.425,
     "",
     "p",
     "",
     ""
    ],
    [
     199.96,
     "",
     "p",
     "",
     ""
    ]
   ],
   "description":"",
   "media_info":{
    "length":{
     "/home/olivier/Downloads/50FPS.mp4":180.05
    },
    "hasAudio":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/video2.avi":true,
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "hasVideo":{
     "/home/olivier/Downloads/video1.avi":true,
     "/home/olivier/Downloads/video2.avi":true,
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "fps":{
     "/home/olivier/Downloads/50FPS.mp4":50.0
    }
   }
  },
  "offset neg":{
   "close_behaviors_between_videos":false,
   "time offset":0.0,
   "file":{
    "1":[
     "/home/olivier/Downloads/50FPS.mp4"
    ],
    "2":[
     "/home/olivier/Downloads/50FPS.mp4"
    ]
   },
   "events":[
    [
     0.01,
     "",
     "p",
     "",
     ""
    ],
    [
     2.2,
     "",
     "p",
     "",
     ""
    ],
    [
     3.5,
     "",
     "p",
     "",
     ""
    ],
    [
     8.18,
     "",
     "p",
     "",
     ""
    ]
   ],
   "time offset second player":-20.0,
   "visualize_spectrogram":false,
   "date":"2016-12-11T00:58:15",
   "description":"",
   "type":"MEDIA",
   "independent_variables":{
    "b":"",
    "a":"",
    "c":"111"
   },
   "media_info":{
    "length":{
     "/home/olivier/Downloads/50FPS.mp4":180.05
    },
    "hasAudio":{
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "hasVideo":{
     "/home/olivier/Downloads/50FPS.mp4":true
    },
    "fps":{
     "/home/olivier/Downloads/50FPS.mp4":50.0
    }
   }
  }
 },
 "independent_variables":{
  "1":{
   "default value":"",
   "label":"b",
   "type":"text",
   "description":"bbbbb"
  },
  "2":{
   "default value":"",
   "label":"c",
   "type":"value from set",
   "description":"cccccc",
   "possible values":"111,222,333"
  },
  "0":{
   "default value":"",
   "label":"a",
   "type":"numeric",
   "description":"aaaaa"
  }
 },
 "behaviors_conf":{
  "1":{
   "modifiers":{},
   "category":"",
   "key":"S",
   "coding map":"",
   "excluded":"",
   "code":"s",
   "type":"State event",
   "description":""
  },
  "0":{
   "modifiers":{},
   "category":"",
   "key":"P",
   "coding map":"",
   "excluded":"",
   "code":"p",
   "type":"Point event",
   "description":""
  }
 },
 "project_format_version":"4.0",
 "project_description":""
}
