# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlgProject(object):
    def setupUi(self, dlgProject):
        dlgProject.setObjectName(_fromUtf8("dlgProject"))
        dlgProject.resize(1121, 973)
        self.verticalLayout_7 = QtGui.QVBoxLayout(dlgProject)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabProject = QtGui.QTabWidget(dlgProject)
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.tabInformation = QtGui.QWidget()
        self.tabInformation.setObjectName(_fromUtf8("tabInformation"))
        self.formLayout = QtGui.QFormLayout(self.tabInformation)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.tabInformation)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label)
        self.leProjectName = QtGui.QLineEdit(self.tabInformation)
        self.leProjectName.setObjectName(_fromUtf8("leProjectName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leProjectName)
        self.lbProjectFilePath = QtGui.QLabel(self.tabInformation)
        self.lbProjectFilePath.setObjectName(_fromUtf8("lbProjectFilePath"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.lbProjectFilePath)
        self.label_7 = QtGui.QLabel(self.tabInformation)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.dteDate = QtGui.QDateTimeEdit(self.tabInformation)
        self.dteDate.setCalendarPopup(True)
        self.dteDate.setObjectName(_fromUtf8("dteDate"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dteDate)
        self.label_6 = QtGui.QLabel(self.tabInformation)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.label_6)
        self.teDescription = QtGui.QPlainTextEdit(self.tabInformation)
        self.teDescription.setObjectName(_fromUtf8("teDescription"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.teDescription)
        self.lbTimeFormat = QtGui.QLabel(self.tabInformation)
        self.lbTimeFormat.setObjectName(_fromUtf8("lbTimeFormat"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.lbTimeFormat)
        self.rbSeconds = QtGui.QRadioButton(self.tabInformation)
        self.rbSeconds.setChecked(True)
        self.rbSeconds.setObjectName(_fromUtf8("rbSeconds"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.rbSeconds)
        self.rbHMS = QtGui.QRadioButton(self.tabInformation)
        self.rbHMS.setObjectName(_fromUtf8("rbHMS"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.rbHMS)
        self.tabProject.addTab(self.tabInformation, _fromUtf8(""))
        self.tabConfiguration = QtGui.QWidget()
        self.tabConfiguration.setObjectName(_fromUtf8("tabConfiguration"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabConfiguration)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.twBehaviors = QtGui.QTableWidget(self.tabConfiguration)
        self.twBehaviors.setAutoFillBackground(False)
        self.twBehaviors.setFrameShadow(QtGui.QFrame.Sunken)
        self.twBehaviors.setMidLineWidth(0)
        self.twBehaviors.setAlternatingRowColors(True)
        self.twBehaviors.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twBehaviors.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twBehaviors.setObjectName(_fromUtf8("twBehaviors"))
        self.twBehaviors.setColumnCount(8)
        self.twBehaviors.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.twBehaviors.setHorizontalHeaderItem(7, item)
        self.twBehaviors.horizontalHeader().setSortIndicatorShown(True)
        self.twBehaviors.verticalHeader().setSortIndicatorShown(False)
        self.horizontalLayout_11.addWidget(self.twBehaviors)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.pbAddBehavior = QtGui.QPushButton(self.tabConfiguration)
        self.pbAddBehavior.setObjectName(_fromUtf8("pbAddBehavior"))
        self.verticalLayout_11.addWidget(self.pbAddBehavior)
        self.pbCloneBehavior = QtGui.QPushButton(self.tabConfiguration)
        self.pbCloneBehavior.setObjectName(_fromUtf8("pbCloneBehavior"))
        self.verticalLayout_11.addWidget(self.pbCloneBehavior)
        self.pbRemoveBehavior = QtGui.QPushButton(self.tabConfiguration)
        self.pbRemoveBehavior.setObjectName(_fromUtf8("pbRemoveBehavior"))
        self.verticalLayout_11.addWidget(self.pbRemoveBehavior)
        self.pbRemoveAllBehaviors = QtGui.QPushButton(self.tabConfiguration)
        self.pbRemoveAllBehaviors.setObjectName(_fromUtf8("pbRemoveAllBehaviors"))
        self.verticalLayout_11.addWidget(self.pbRemoveAllBehaviors)
        self.pbBehaviorsCategories = QtGui.QPushButton(self.tabConfiguration)
        self.pbBehaviorsCategories.setObjectName(_fromUtf8("pbBehaviorsCategories"))
        self.verticalLayout_11.addWidget(self.pbBehaviorsCategories)
        self.pb_convert_behav_keys_to_lower = QtGui.QPushButton(self.tabConfiguration)
        self.pb_convert_behav_keys_to_lower.setObjectName(_fromUtf8("pb_convert_behav_keys_to_lower"))
        self.verticalLayout_11.addWidget(self.pb_convert_behav_keys_to_lower)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.pbExclusionMatrix = QtGui.QPushButton(self.tabConfiguration)
        self.pbExclusionMatrix.setObjectName(_fromUtf8("pbExclusionMatrix"))
        self.verticalLayout_11.addWidget(self.pbExclusionMatrix)
        self.pbImportBehaviorsFromProject = QtGui.QPushButton(self.tabConfiguration)
        self.pbImportBehaviorsFromProject.setObjectName(_fromUtf8("pbImportBehaviorsFromProject"))
        self.verticalLayout_11.addWidget(self.pbImportBehaviorsFromProject)
        self.pbImportFromJWatcher = QtGui.QPushButton(self.tabConfiguration)
        self.pbImportFromJWatcher.setEnabled(True)
        self.pbImportFromJWatcher.setObjectName(_fromUtf8("pbImportFromJWatcher"))
        self.verticalLayout_11.addWidget(self.pbImportFromJWatcher)
        self.pbImportFromTextFile = QtGui.QPushButton(self.tabConfiguration)
        self.pbImportFromTextFile.setObjectName(_fromUtf8("pbImportFromTextFile"))
        self.verticalLayout_11.addWidget(self.pbImportFromTextFile)
        self.pbExportEthogram = QtGui.QPushButton(self.tabConfiguration)
        self.pbExportEthogram.setObjectName(_fromUtf8("pbExportEthogram"))
        self.verticalLayout_11.addWidget(self.pbExportEthogram)
        self.horizontalLayout_11.addLayout(self.verticalLayout_11)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.lbObservationsState = QtGui.QLabel(self.tabConfiguration)
        self.lbObservationsState.setObjectName(_fromUtf8("lbObservationsState"))
        self.verticalLayout_5.addWidget(self.lbObservationsState)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.tabProject.addTab(self.tabConfiguration, _fromUtf8(""))
        self.tabSubjects = QtGui.QWidget()
        self.tabSubjects.setObjectName(_fromUtf8("tabSubjects"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tabSubjects)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.twSubjects = QtGui.QTableWidget(self.tabSubjects)
        self.twSubjects.setAutoFillBackground(False)
        self.twSubjects.setFrameShadow(QtGui.QFrame.Sunken)
        self.twSubjects.setMidLineWidth(0)
        self.twSubjects.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twSubjects.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twSubjects.setObjectName(_fromUtf8("twSubjects"))
        self.twSubjects.setColumnCount(3)
        self.twSubjects.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twSubjects.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twSubjects.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twSubjects.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_12.addWidget(self.twSubjects)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.pbAddSubject = QtGui.QPushButton(self.tabSubjects)
        self.pbAddSubject.setObjectName(_fromUtf8("pbAddSubject"))
        self.verticalLayout_15.addWidget(self.pbAddSubject)
        self.pbRemoveSubject = QtGui.QPushButton(self.tabSubjects)
        self.pbRemoveSubject.setObjectName(_fromUtf8("pbRemoveSubject"))
        self.verticalLayout_15.addWidget(self.pbRemoveSubject)
        self.pb_convert_subjects_key_to_lower = QtGui.QPushButton(self.tabSubjects)
        self.pb_convert_subjects_key_to_lower.setObjectName(_fromUtf8("pb_convert_subjects_key_to_lower"))
        self.verticalLayout_15.addWidget(self.pb_convert_subjects_key_to_lower)
        self.pbImportSubjectsFromProject = QtGui.QPushButton(self.tabSubjects)
        self.pbImportSubjectsFromProject.setObjectName(_fromUtf8("pbImportSubjectsFromProject"))
        self.verticalLayout_15.addWidget(self.pbImportSubjectsFromProject)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.lbSubjectsState = QtGui.QLabel(self.tabSubjects)
        self.lbSubjectsState.setObjectName(_fromUtf8("lbSubjectsState"))
        self.verticalLayout_14.addWidget(self.lbSubjectsState)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.tabProject.addTab(self.tabSubjects, _fromUtf8(""))
        self.tabIndependentVariables = QtGui.QWidget()
        self.tabIndependentVariables.setObjectName(_fromUtf8("tabIndependentVariables"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.tabIndependentVariables)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.twVariables = QtGui.QTableWidget(self.tabIndependentVariables)
        self.twVariables.setAutoFillBackground(False)
        self.twVariables.setFrameShadow(QtGui.QFrame.Sunken)
        self.twVariables.setMidLineWidth(0)
        self.twVariables.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twVariables.setDragDropOverwriteMode(False)
        self.twVariables.setAlternatingRowColors(True)
        self.twVariables.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twVariables.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twVariables.setObjectName(_fromUtf8("twVariables"))
        self.twVariables.setColumnCount(5)
        self.twVariables.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.twVariables.setHorizontalHeaderItem(4, item)
        self.twVariables.horizontalHeader().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.twVariables)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.leLabel = QtGui.QLineEdit(self.tabIndependentVariables)
        self.leLabel.setObjectName(_fromUtf8("leLabel"))
        self.horizontalLayout_3.addWidget(self.leLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.leDescription = QtGui.QLineEdit(self.tabIndependentVariables)
        self.leDescription.setObjectName(_fromUtf8("leDescription"))
        self.horizontalLayout_5.addWidget(self.leDescription)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_8.setMinimumSize(QtCore.QSize(120, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.cbType = QtGui.QComboBox(self.tabIndependentVariables)
        self.cbType.setMinimumSize(QtCore.QSize(120, 0))
        self.cbType.setObjectName(_fromUtf8("cbType"))
        self.horizontalLayout_6.addWidget(self.cbType)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lePredefined = QtGui.QLineEdit(self.tabIndependentVariables)
        self.lePredefined.setObjectName(_fromUtf8("lePredefined"))
        self.horizontalLayout_7.addWidget(self.lePredefined)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_9.setMinimumSize(QtCore.QSize(120, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.dte_default_date = QtGui.QDateTimeEdit(self.tabIndependentVariables)
        self.dte_default_date.setObjectName(_fromUtf8("dte_default_date"))
        self.horizontalLayout_8.addWidget(self.dte_default_date)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.tabIndependentVariables)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.leSetValues = QtGui.QLineEdit(self.tabIndependentVariables)
        self.leSetValues.setObjectName(_fromUtf8("leSetValues"))
        self.horizontalLayout_9.addWidget(self.leSetValues)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pbAddVariable = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbAddVariable.setObjectName(_fromUtf8("pbAddVariable"))
        self.verticalLayout_12.addWidget(self.pbAddVariable)
        self.pbRemoveVariable = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbRemoveVariable.setObjectName(_fromUtf8("pbRemoveVariable"))
        self.verticalLayout_12.addWidget(self.pbRemoveVariable)
        self.pbImportVarFromProject = QtGui.QPushButton(self.tabIndependentVariables)
        self.pbImportVarFromProject.setObjectName(_fromUtf8("pbImportVarFromProject"))
        self.verticalLayout_12.addWidget(self.pbImportVarFromProject)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.tabProject.addTab(self.tabIndependentVariables, _fromUtf8(""))
        self.tabObservations = QtGui.QWidget()
        self.tabObservations.setObjectName(_fromUtf8("tabObservations"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabObservations)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.twObservations = QtGui.QTableWidget(self.tabObservations)
        self.twObservations.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twObservations.setDragDropOverwriteMode(False)
        self.twObservations.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.twObservations.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twObservations.setWordWrap(False)
        self.twObservations.setObjectName(_fromUtf8("twObservations"))
        self.twObservations.setColumnCount(4)
        self.twObservations.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twObservations.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.twObservations)
        self.pbRemoveObservation = QtGui.QPushButton(self.tabObservations)
        self.pbRemoveObservation.setObjectName(_fromUtf8("pbRemoveObservation"))
        self.verticalLayout.addWidget(self.pbRemoveObservation)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabProject.addTab(self.tabObservations, _fromUtf8(""))
        self.tabBehavCodingMap = QtGui.QWidget()
        self.tabBehavCodingMap.setObjectName(_fromUtf8("tabBehavCodingMap"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabBehavCodingMap)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.twBehavCodingMap = QtGui.QTableWidget(self.tabBehavCodingMap)
        self.twBehavCodingMap.setAutoFillBackground(False)
        self.twBehavCodingMap.setFrameShadow(QtGui.QFrame.Sunken)
        self.twBehavCodingMap.setMidLineWidth(0)
        self.twBehavCodingMap.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.twBehavCodingMap.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.twBehavCodingMap.setObjectName(_fromUtf8("twBehavCodingMap"))
        self.twBehavCodingMap.setColumnCount(2)
        self.twBehavCodingMap.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.twBehavCodingMap.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twBehavCodingMap.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.twBehavCodingMap)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pbAddBehaviorsCodingMap = QtGui.QPushButton(self.tabBehavCodingMap)
        self.pbAddBehaviorsCodingMap.setObjectName(_fromUtf8("pbAddBehaviorsCodingMap"))
        self.verticalLayout_4.addWidget(self.pbAddBehaviorsCodingMap)
        self.pbRemoveBehaviorsCodingMap = QtGui.QPushButton(self.tabBehavCodingMap)
        self.pbRemoveBehaviorsCodingMap.setObjectName(_fromUtf8("pbRemoveBehaviorsCodingMap"))
        self.verticalLayout_4.addWidget(self.pbRemoveBehaviorsCodingMap)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem9)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.tabProject.addTab(self.tabBehavCodingMap, _fromUtf8(""))
        self.tab_time_converters = QtGui.QWidget()
        self.tab_time_converters.setObjectName(_fromUtf8("tab_time_converters"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab_time_converters)
        self.verticalLayout_18.setMargin(0)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_11 = QtGui.QLabel(self.tab_time_converters)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_18.addWidget(self.label_11)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tw_converters = QtGui.QTableWidget(self.tab_time_converters)
        self.tw_converters.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tw_converters.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tw_converters.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tw_converters.setObjectName(_fromUtf8("tw_converters"))
        self.tw_converters.setColumnCount(3)
        self.tw_converters.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tw_converters.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tw_converters.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tw_converters.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_16.addWidget(self.tw_converters)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.pb_add_converter = QtGui.QPushButton(self.tab_time_converters)
        self.pb_add_converter.setObjectName(_fromUtf8("pb_add_converter"))
        self.verticalLayout_17.addWidget(self.pb_add_converter)
        self.pb_modify_converter = QtGui.QPushButton(self.tab_time_converters)
        self.pb_modify_converter.setObjectName(_fromUtf8("pb_modify_converter"))
        self.verticalLayout_17.addWidget(self.pb_modify_converter)
        self.pb_delete_converter = QtGui.QPushButton(self.tab_time_converters)
        self.pb_delete_converter.setObjectName(_fromUtf8("pb_delete_converter"))
        self.verticalLayout_17.addWidget(self.pb_delete_converter)
        self.pb_load_from_file = QtGui.QPushButton(self.tab_time_converters)
        self.pb_load_from_file.setObjectName(_fromUtf8("pb_load_from_file"))
        self.verticalLayout_17.addWidget(self.pb_load_from_file)
        self.pb_load_from_repo = QtGui.QPushButton(self.tab_time_converters)
        self.pb_load_from_repo.setObjectName(_fromUtf8("pb_load_from_repo"))
        self.verticalLayout_17.addWidget(self.pb_load_from_repo)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem10)
        self.horizontalLayout_16.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_13 = QtGui.QLabel(self.tab_time_converters)
        self.label_13.setMinimumSize(QtCore.QSize(120, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.le_converter_name = QtGui.QLineEdit(self.tab_time_converters)
        self.le_converter_name.setObjectName(_fromUtf8("le_converter_name"))
        self.horizontalLayout_17.addWidget(self.le_converter_name)
        spacerItem11 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.tab_time_converters)
        self.label_10.setMinimumSize(QtCore.QSize(120, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.le_converter_description = QtGui.QLineEdit(self.tab_time_converters)
        self.le_converter_description.setObjectName(_fromUtf8("le_converter_description"))
        self.horizontalLayout_10.addWidget(self.le_converter_description)
        spacerItem12 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.verticalLayout_18.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_12 = QtGui.QLabel(self.tab_time_converters)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12)
        self.pb_code_help = QtGui.QPushButton(self.tab_time_converters)
        self.pb_code_help.setObjectName(_fromUtf8("pb_code_help"))
        self.verticalLayout_9.addWidget(self.pb_code_help)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem13)
        self.horizontalLayout_2.addLayout(self.verticalLayout_9)
        self.pteCode = QtGui.QPlainTextEdit(self.tab_time_converters)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.pteCode.setFont(font)
        self.pteCode.setObjectName(_fromUtf8("pteCode"))
        self.horizontalLayout_2.addWidget(self.pteCode)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.pb_save_converter = QtGui.QPushButton(self.tab_time_converters)
        self.pb_save_converter.setObjectName(_fromUtf8("pb_save_converter"))
        self.verticalLayout_13.addWidget(self.pb_save_converter)
        self.pb_cancel_converter = QtGui.QPushButton(self.tab_time_converters)
        self.pb_cancel_converter.setObjectName(_fromUtf8("pb_cancel_converter"))
        self.verticalLayout_13.addWidget(self.pb_cancel_converter)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.tabProject.addTab(self.tab_time_converters, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabProject)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.pbCancel = QtGui.QPushButton(dlgProject)
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.horizontalLayout_4.addWidget(self.pbCancel)
        self.pbOK = QtGui.QPushButton(dlgProject)
        self.pbOK.setObjectName(_fromUtf8("pbOK"))
        self.horizontalLayout_4.addWidget(self.pbOK)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)

        self.retranslateUi(dlgProject)
        self.tabProject.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(dlgProject)

    def retranslateUi(self, dlgProject):
        dlgProject.setWindowTitle(_translate("dlgProject", "Project", None))
        self.label.setText(_translate("dlgProject", "Project name", None))
        self.lbProjectFilePath.setText(_translate("dlgProject", "Project file path:", None))
        self.label_7.setText(_translate("dlgProject", "Date", None))
        self.dteDate.setDisplayFormat(_translate("dlgProject", "yyyy-MM-dd hh:mm", None))
        self.label_6.setText(_translate("dlgProject", "Description", None))
        self.lbTimeFormat.setText(_translate("dlgProject", "Time format", None))
        self.rbSeconds.setText(_translate("dlgProject", "seconds", None))
        self.rbHMS.setText(_translate("dlgProject", "hh:mm:ss.mss", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabInformation), _translate("dlgProject", "Information", None))
        self.twBehaviors.setSortingEnabled(True)
        item = self.twBehaviors.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "Behavior type", None))
        item = self.twBehaviors.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Key", None))
        item = self.twBehaviors.horizontalHeaderItem(2)
        item.setText(_translate("dlgProject", "Code", None))
        item = self.twBehaviors.horizontalHeaderItem(3)
        item.setText(_translate("dlgProject", "Description", None))
        item = self.twBehaviors.horizontalHeaderItem(4)
        item.setText(_translate("dlgProject", "Category", None))
        item = self.twBehaviors.horizontalHeaderItem(5)
        item.setText(_translate("dlgProject", "Modifiers", None))
        item = self.twBehaviors.horizontalHeaderItem(6)
        item.setText(_translate("dlgProject", "Exclusion", None))
        item = self.twBehaviors.horizontalHeaderItem(7)
        item.setText(_translate("dlgProject", "Modifiers coding map", None))
        self.pbAddBehavior.setText(_translate("dlgProject", "Add behavior", None))
        self.pbCloneBehavior.setText(_translate("dlgProject", "Clone behavior", None))
        self.pbRemoveBehavior.setText(_translate("dlgProject", "Remove behavior", None))
        self.pbRemoveAllBehaviors.setText(_translate("dlgProject", "Remove all behaviors", None))
        self.pbBehaviorsCategories.setText(_translate("dlgProject", "Behavioral categories", None))
        self.pb_convert_behav_keys_to_lower.setText(_translate("dlgProject", "Convert keys to lower case", None))
        self.pbExclusionMatrix.setText(_translate("dlgProject", "Exclusion matrix", None))
        self.pbImportBehaviorsFromProject.setText(_translate("dlgProject", "Import behaviors\n"
"from a BORIS project", None))
        self.pbImportFromJWatcher.setText(_translate("dlgProject", "Import from JWatcher", None))
        self.pbImportFromTextFile.setText(_translate("dlgProject", "Import from text file", None))
        self.pbExportEthogram.setText(_translate("dlgProject", "Export Ethogram", None))
        self.lbObservationsState.setText(_translate("dlgProject", "TextLabel", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabConfiguration), _translate("dlgProject", "Ethogram", None))
        self.twSubjects.setSortingEnabled(True)
        item = self.twSubjects.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "Key", None))
        item = self.twSubjects.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Subject name", None))
        item = self.twSubjects.horizontalHeaderItem(2)
        item.setText(_translate("dlgProject", "Description", None))
        self.pbAddSubject.setText(_translate("dlgProject", "Add subject", None))
        self.pbRemoveSubject.setText(_translate("dlgProject", "Remove subject", None))
        self.pb_convert_subjects_key_to_lower.setText(_translate("dlgProject", "Convert keys to lower case", None))
        self.pbImportSubjectsFromProject.setText(_translate("dlgProject", "Import subjects\n"
"from a BORIS project", None))
        self.lbSubjectsState.setText(_translate("dlgProject", "TextLabel", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabSubjects), _translate("dlgProject", "Subjects", None))
        self.twVariables.setSortingEnabled(True)
        item = self.twVariables.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "Label", None))
        item = self.twVariables.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Description", None))
        item = self.twVariables.horizontalHeaderItem(2)
        item.setText(_translate("dlgProject", "Type", None))
        item = self.twVariables.horizontalHeaderItem(3)
        item.setText(_translate("dlgProject", "Predefined value", None))
        item = self.twVariables.horizontalHeaderItem(4)
        item.setText(_translate("dlgProject", "Set of values", None))
        self.label_2.setText(_translate("dlgProject", "Label", None))
        self.label_3.setText(_translate("dlgProject", "Description", None))
        self.label_8.setText(_translate("dlgProject", "Type", None))
        self.label_4.setText(_translate("dlgProject", "Predefined value", None))
        self.label_9.setText(_translate("dlgProject", "Predefined date", None))
        self.dte_default_date.setDisplayFormat(_translate("dlgProject", "yyyy-MM-dd hh:mm", None))
        self.label_5.setText(_translate("dlgProject", "Set of values (separated by comma)", None))
        self.pbAddVariable.setText(_translate("dlgProject", "Add variable", None))
        self.pbRemoveVariable.setText(_translate("dlgProject", "Remove variable", None))
        self.pbImportVarFromProject.setText(_translate("dlgProject", "Import variables\n"
"from a BORIS project", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabIndependentVariables), _translate("dlgProject", "Independent variables", None))
        item = self.twObservations.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "id", None))
        item = self.twObservations.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Date", None))
        item = self.twObservations.horizontalHeaderItem(2)
        item.setText(_translate("dlgProject", "Description", None))
        item = self.twObservations.horizontalHeaderItem(3)
        item.setText(_translate("dlgProject", "Media", None))
        self.pbRemoveObservation.setText(_translate("dlgProject", "Remove selected observations", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabObservations), _translate("dlgProject", "Observations", None))
        self.twBehavCodingMap.setSortingEnabled(True)
        item = self.twBehavCodingMap.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "Name", None))
        item = self.twBehavCodingMap.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Behavior codes", None))
        self.pbAddBehaviorsCodingMap.setText(_translate("dlgProject", "Add a behaviors coding map", None))
        self.pbRemoveBehaviorsCodingMap.setText(_translate("dlgProject", "Remove behaviors coding map", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tabBehavCodingMap), _translate("dlgProject", "Behaviors coding map", None))
        self.label_11.setText(_translate("dlgProject", "Time converters for external data", None))
        self.tw_converters.setSortingEnabled(True)
        item = self.tw_converters.horizontalHeaderItem(0)
        item.setText(_translate("dlgProject", "Name", None))
        item = self.tw_converters.horizontalHeaderItem(1)
        item.setText(_translate("dlgProject", "Description", None))
        item = self.tw_converters.horizontalHeaderItem(2)
        item.setText(_translate("dlgProject", "Code", None))
        self.pb_add_converter.setText(_translate("dlgProject", "Add new converter", None))
        self.pb_modify_converter.setText(_translate("dlgProject", "Modify converter", None))
        self.pb_delete_converter.setText(_translate("dlgProject", "Delete converter", None))
        self.pb_load_from_file.setText(_translate("dlgProject", "Load converters from file", None))
        self.pb_load_from_repo.setText(_translate("dlgProject", "Load converters from BORIS repository", None))
        self.label_13.setText(_translate("dlgProject", "Name", None))
        self.label_10.setText(_translate("dlgProject", "Description", None))
        self.label_12.setText(_translate("dlgProject", "Python code", None))
        self.pb_code_help.setText(_translate("dlgProject", "Help", None))
        self.pb_save_converter.setText(_translate("dlgProject", "Save converter", None))
        self.pb_cancel_converter.setText(_translate("dlgProject", "Cancel", None))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_time_converters), _translate("dlgProject", "Converters", None))
        self.pbCancel.setText(_translate("dlgProject", "Cancel", None))
        self.pbOK.setText(_translate("dlgProject", "OK", None))

