# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'boris/video_equalizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Equalizer(object):
    def setupUi(self, Equalizer):
        Equalizer.setObjectName("Equalizer")
        Equalizer.resize(262, 325)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Equalizer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(Equalizer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Equalizer)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.hs_brightness = QtWidgets.QSlider(Equalizer)
        self.hs_brightness.setMinimum(-100)
        self.hs_brightness.setProperty("value", 0)
        self.hs_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.hs_brightness.setObjectName("hs_brightness")
        self.gridLayout.addWidget(self.hs_brightness, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Equalizer)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.hs_contrast = QtWidgets.QSlider(Equalizer)
        self.hs_contrast.setMinimum(-100)
        self.hs_contrast.setProperty("value", 0)
        self.hs_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.hs_contrast.setObjectName("hs_contrast")
        self.gridLayout.addWidget(self.hs_contrast, 1, 2, 1, 2)
        self.label_3 = QtWidgets.QLabel(Equalizer)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.hs_saturation = QtWidgets.QSlider(Equalizer)
        self.hs_saturation.setMinimum(-100)
        self.hs_saturation.setProperty("value", 0)
        self.hs_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.hs_saturation.setObjectName("hs_saturation")
        self.gridLayout.addWidget(self.hs_saturation, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Equalizer)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.hs_gamma = QtWidgets.QSlider(Equalizer)
        self.hs_gamma.setMinimum(-100)
        self.hs_gamma.setProperty("value", 0)
        self.hs_gamma.setOrientation(QtCore.Qt.Horizontal)
        self.hs_gamma.setObjectName("hs_gamma")
        self.gridLayout.addWidget(self.hs_gamma, 3, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(Equalizer)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.hs_hue = QtWidgets.QSlider(Equalizer)
        self.hs_hue.setMinimum(-100)
        self.hs_hue.setProperty("value", 0)
        self.hs_hue.setOrientation(QtCore.Qt.Horizontal)
        self.hs_hue.setObjectName("hs_hue")
        self.gridLayout.addWidget(self.hs_hue, 4, 1, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_close = QtWidgets.QPushButton(Equalizer)
        self.pb_close.setObjectName("pb_close")
        self.horizontalLayout.addWidget(self.pb_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Equalizer)
        QtCore.QMetaObject.connectSlotsByName(Equalizer)

    def retranslateUi(self, Equalizer):
        _translate = QtCore.QCoreApplication.translate
        Equalizer.setWindowTitle(_translate("Equalizer", "Edit event"))
        self.label_6.setText(_translate("Equalizer", "Video equalizer"))
        self.label.setText(_translate("Equalizer", "Brightness"))
        self.label_2.setText(_translate("Equalizer", "Contrast"))
        self.label_3.setText(_translate("Equalizer", "Saturation"))
        self.label_4.setText(_translate("Equalizer", "Gamma"))
        self.label_5.setText(_translate("Equalizer", "Hue"))
        self.pb_close.setText(_translate("Equalizer", "Close"))
